/*

try {
  tryCode - Code block to run
}
catch(err) {
  catchCode - Code block to handle errors
}
finally {
  finallyCode - Code block to be executed regardless of the try result
}

*/
//code
const numerator= 100, denominator = 10; //"a"

// try {
//      console.log(numerator/denominator);
//     //  console.log(a);
// }
// catch(error) {
//     // console.log('An error caught'); 
//     console.log('Error message: ' + error);  
// }
// finally {
//      console.log('Finally will execute every time');
// }



